// @flow
const USER_FETCH_REQUEST = "USER_FETCH_REQUEST";
const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS";
const USER_FETCH_FAIL = "USER_FETCH_FAIL";

export { USER_FETCH_REQUEST, USER_FETCH_SUCCESS, USER_FETCH_FAIL };
