// flow-typed signature: f1658e32f85548bbc471468d0589858d
// flow-typed version: <<STUB>>/react-native-fast-image_v5.1.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-fast-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-fast-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-fast-image/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-fast-image/src/index.js' {
  declare module.exports: $Exports<'react-native-fast-image/src/index'>;
}
